### ISSUE TITLE
LexError no span information

### ISSUE THREAD

**Issue by Dushistov** [alexcrichton/proc-macro2#178]
If I run code bellow via `cargo run`, it prints:

```
err: LexError, at 1:0 - 1:0
```

As you see the location information is wrong, it should be line 3, not 1.
According to code of syn, this is because of `LexError` have no 
method like `fn span(&sefl) -> Span`, so syn just call `Span::call_site`,
and this method provides meaningless span for usage inside `build.rs` / `main.rs` 

```toml
#Cargo.toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Rust Example <rust-snippet@example.com>"]
edition = "2018"

[dependencies]
syn = { version = "*", features = ["full", "extra-traits", "visit-mut", "visit"] }
proc-macro2 = { version = "*", features = ["span-locations"] }
```

```Rust
//main.rs
fn main() {
    if let Err(err) = syn::parse_file(
        r#"
//comment
macro_call!(};
"#,
    ) {
        println!(
            "err: {}, at {}:{} - {}:{}",
            err,
            err.span().start().line,
            err.span().start().column,
            err.span().end().line,
            err.span().end().column
        );
    }
}
```
