### ISSUE TITLE
Unstable feature broken - pm::Span no longer Default

### ISSUE THREAD

**Issue by Arnavion** [alexcrichton/proc-macro2#30]
https://github.com/rust-lang/rust/commit/74cc1fdb52379320bc5dd3f48366d04f0a97d614

```
error[E0277]: the trait bound `proc_macro::Span: std::default::Default` is not satisfied
   --> C:\Users\Arnavion\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.1.3\src\unstable.rs:163:17
    |
163 | pub struct Span(proc_macro::Span);
    |                 ^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `proc_macro::Span`
    |
    = note: required by `std::default::Default::default`
```

```diff
--- src/unstable.rs.orig        2017-11-19 01:22:18.446739600 -0800
+++ src/unstable.rs     2017-11-19 01:16:34.641581800 -0800
@@ -159,9 +159,15 @@ impl fmt::Debug for TokenTreeIter {
     }
 }

-#[derive(Copy, Clone, Default)]
+#[derive(Copy, Clone)]
 pub struct Span(proc_macro::Span);

+impl Default for Span {
+    fn default() -> Self {
+        Span(proc_macro::Span::def_site())
+    }
+}
+
 impl Span {
     pub fn call_site() -> Span {
         Span(proc_macro::Span::call_site())
```

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/proc-macro2/commit/998f642a73284a89c3de553e977a0683cb06bf66, thanks!

**Comment by SeunLanLege** [comment]
I'm not sure why i have this issue, even though it's been fixed

cargo.toml

```toml
[package]
name = "impl-service"
version = "0.1.0"
authors = ["seunlanlege <seunlanlege@gmail.com>"]

[dependencies]
quote = { git = 'https://github.com/dtolnay/quote' }
proc-macro2 = { version = "0.2", features = ["nightly"] }



[lib]
proc-macro = true

[dependencies.syn]
git = 'https://github.com/dtolnay/syn'
features = ["full", "fold", "parsing", "printing", "extra-traits"]
default-features = false

```
