### ISSUE TITLE
Show semver exempt APIs on docs.rs

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#82]
I believe something not entirely unlike the following may do the trick but let's keep this issue open until we confirm everything we expect is visible in http://docs.rs/proc-macro2.

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--cfg procmacro2_semver_exempt"]
```

Requires #81.
